### ISSUE TITLE
Projects not listing

### ISSUE THREAD

**Issue by servetoz32** [swdotcom/swdc-vscode#133]
Hi,

I just installed the extension but I cannot see any Project.
How will  the Projects be determined? By git repo, folder name, workspace?
I cannot review Project summary because of that.
And I'm working on WSL 2.0, if it makes any different.

Thank you.

**ISSUE TYPE**
- Bug Report

**Screenshots**
![image](https://user-images.githubusercontent.com/14264923/91397731-e3283900-e83b-11ea-9cf7-14883bf3f5ef.png)

**Desktop (please complete the following information):**
 - OS: Windows on WSL 2.0
 - Plugin version [e.g. Code Time v2.3.0]

**Comment by bjacobson26** [comment]
Hi @servetoz32 - thank you for opening up this issue.

Projects will be determined by their repository name:
![image](https://user-images.githubusercontent.com/9271952/91749689-b98e4b00-eb76-11ea-9131-238418accbf6.png)

Was CodeTime installed while you were working in the project(s) you expect to be able to view a summary for? Once the plugin is installed, you should be able to view the project summary after some data has been collected. Let me know if the problem persists.

**Comment by servetoz32** [comment]
Hi @bjacobson26 ,

My project that Im currently working on has not git config yet. And as I said I'm working on WSL 2.0, so project's directory is being seen by vscode as remote server. But when I open a normal project that is not on WSL 2.0 and without git, plugin detected the project as folder name. So, this is maybe not a bug and I can say it is feature request for WSL support.

Thanks.

**Comment by bjacobson26** [comment]
👍 

We have an open issue for WSL: https://github.com/swdotcom/swdc-vscode/issues/87

We just deployed CodeTime v2.3.6 and that may have the fix for you. 

Going to close this issue for now, but feel free to re-open if you continue to encounter issues. Thank you!

**Comment by tinemlakar** [comment]
I've just noticed that my project are not listing anymore. It used to work OK. I've probably updated plugin a few times since I last use this feature, so I'm not sure what version it was since it last worked. I updated today to last version (2.3.21) and still doesn't work - empty project list. I don't work on WSL.

My config: WIN 10 x64, VS Code 1.46.1, NodeJs 12.8.1
