### ISSUE TITLE
Cannot read property 'id' of null

### ISSUE THREAD

**Issue by rexarski** [swdotcom/swdc-vscode#136]
**Describe the bug**
I got an error pop-up stating "Cannot read property 'id' of null" every time I tried to log in.

**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

1. Install the extension from VSC.
2. Open Code Time extension.
3. Click on "Log in with Google".
4. See the page that Google asks me for the permission, click on "Ok".
5. See the error.
6. Repeat with "Log in with GitHub" and "Log in with email".
7. See the error again.

**Expected behavior**
Successfully log in.

**Screenshot**
![Screen Shot 2020-08-31 at 8 03 40 PM](https://user-images.githubusercontent.com/4172477/91710238-49f47c00-ebc7-11ea-8d90-5c8e9c000989.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.6
 - Plugin version: v2.3.2

**Additional context**
- Tried the previous steps with my adblocker turned off. The result was the same.

**Comment by bjacobson26** [comment]
Hi @rexarski - thank you for reporting this issue. We apologize for the inconvenience. We are currently looking into the error and will get back to you ASAP.

**Comment by bjacobson26** [comment]
@rexarski - we have deployed an update that will hopefully resolve your issue. if not, please let me know and we can try something else. Thank you!

**Comment by Deboleto** [comment]
im facing the same error right now :(

**Comment by bjacobson26** [comment]
hi @Deboleto - thank you for letting us know. I'd like to get some more info - can you email me at bo@software.com with the following info:

- CodeTime version
- browser info
- email that you are trying to login / sign up with. 

thank you!

**Comment by bjacobson26** [comment]
I'm curious if clearing the browser cache / deleting any cookies associated with software.com will resolve the issue.

**Comment by rexarski** [comment]
> Hi @rexarski - thank you for reporting this issue. We apologize for the inconvenience. We are currently looking into the error and will get back to you ASAP.

I've tried version v2.3.3 and cleared cache and cookies as well. Still have that problem. :(

**Comment by bjacobson26** [comment]
@rexarski - we've identified the problem area, but could use some more info to help resolve the issue. I'd like to get some more info from you if possible. Would you mind emailing me at bo@software.com. Thank you!

**Comment by bjacobson26** [comment]
Hi @rexarski  and @Deboleto - we found the problem. 

We found a place in the code where it's possible for an invalid jwt token to be set in your `.software` folder. We're implementing a fix today. Unfortunately, the fix will not be able to resolve the bad token in that folder. So - two options. If you want to save your codetime history for your anonymous user account, please email me and I can help by fixing your `.software` folder. If you do not care about losing your local history, deleting your `.software` folder and restarting vscode should resolve the issue.

**Comment by Deboleto** [comment]
Thank you @bjacobson26 !

**Comment by rexarski** [comment]
Actually it was my first time installing Code Time so deleting `.software` saves the day for me. Thank you @bjacobson26 !
